/**
 * Generated by tools/status-vocabulary.mjs from the Showdown data shipped with Cobblemon; edit the tool, not this file.
 *
 * Shared identity for combatant states. Consumers ask "does this actor carry the tag" and never depend on a
 * producer's effect id; producers either apply the shared default effect for a name or declare their own
 * variant in startup.ts with `.tag(StatusVocabulary.tag(name))`. New concepts can use their own names
 * with the same tag convention; behavior is defined by the content and available implementations.
 */
namespace StatusVocabulary {
    export var namespace = "world_combat";
    /** Names of the shared default major statuses; Cobblemon native ids share these names. */
    export var majorNames: string[] = ["burn","paralysis","sleep","frozen","poison","toxic"];
    /** Showdown code -> project name, for reading move/ability data. */
    export var showdownMajor: { [code: string]: string } = {"brn":"burn","par":"paralysis","slp":"sleep","frz":"frozen","psn":"poison","tox":"toxic"};
    /** Volatile conditions consumed anywhere in moves, abilities, items or the engine (103). */
    export var volatile: string[] = ["allyswitch","aquaring","attract","banefulbunker","beakblast","bide","bounce","burningbulwark","charge","choicelock","commanded","commanding","confusion","counter","cudchew","curse","defensecurl","destinybond","disable","dragoncheer","dynamax","electrify","embargo","encore","endure","flashfire","flinch","fling","fly","focusenergy","focuspunch","followme","foresight","furycutter","gastroacid","gem","glaiverush","gmaxchistrike","grudge","healblock","helpinghand","iceball","imprison","ingrain","kingsshield","laserfocus","leechseed","leppaberry","lockedmove","lockon","magiccoat","magnetrise","maxguard","mefirst","metronome","micleberry","minimize","miracleeye","mirrorcoat","mustrecharge","nightmare","noretreat","obstruct","octolock","partiallytrapped","perishsong","powder","powershift","powertrick","protect","protosynthesis","quarkdrive","rage","ragepowder","rollout","rolloutstorage","roost","saltcure","shelltrap","silktrap","skydrop","slowstart","smackdown","snatch","sparklingaria","spikyshield","spotlight","stall","stockpile","substitute","syrupbomb","tarshot","taunt","telekinesis","throatchop","torment","trapped","truant","twoturnmove","unburden","uproar","yawn","zenmode"];
    /** Field-level concepts (not combatant states); shared ids use `world_combat:field/<name>` when they become shared. */
    export var field: { [kind: string]: string[] } = {"side":["auroraveil","craftyshield","lightscreen","luckychant","matblock","mist","quickguard","reflect","safeguard","spikes","stealthrock","stickyweb","tailwind","toxicspikes","waterpledge","wideguard"],"weather":["deltastream","desolateland","hail","primordialsea","raindance","sandstorm","snow","sunnyday"],"terrain":["electricterrain","grassyterrain","mistyterrain","psychicterrain"],"pseudoWeather":["fairylock","gravity","iondeluge","magicroom","mudsport","trickroom","watersport","wonderroom"],"slot":["healingwish","lunardance","revivalblessing","wish"]};
    export function tag(name: string): string { return namespace + ":status/" + name; }
    export function fieldId(name: string): string { return namespace + ":field/" + name; }
    export function major(name: string): boolean { return majorNames.indexOf(name) >= 0; }
    export function known(name: string): boolean { return major(name) || volatile.indexOf(name) >= 0; }
    /** Vocabulary name embedded in an effect path (`world_combat:thunderwave_paralysis` -> `paralysis`), or "". */
    export function embedded(effectId: string): string {
        var pathPart = String(effectId).split(":").pop() || "", parts = pathPart.split(/[^a-z0-9]+/);
        for (var i = 0; i < parts.length; i++) if (known(parts[i])) return parts[i];
        return "";
    }
}
