package dev.worldcombat.core.client.particles;

import dev.worldcombat.core.WorldCombatCore;
import java.io.BufferedReader;
import java.io.IOException;
import java.io.InputStream;
import java.io.InputStreamReader;
import java.nio.charset.StandardCharsets;
import java.util.ArrayList;
import java.util.List;
import net.minecraft.core.particles.ParticleType;
import net.minecraft.core.particles.SimpleParticleType;
import net.minecraft.core.registries.Registries;
import net.neoforged.bus.api.IEventBus;
import net.neoforged.neoforge.registries.DeferredHolder;
import net.neoforged.neoforge.registries.DeferredRegister;

/**
 * Registers one {@link SimpleParticleType} per Cobblemon particle texture listed in
 * {@code assets/world_combat_core/particle_types.txt} (generated by
 * {@code tools/generate-particle-types.mjs}). The matching
 * {@code assets/world_combat_core/particles/<id>.json} lists the Cobblemon sprite so the client can
 * build a SpriteSet for it; MadParticle reads that SpriteSet and renders the particle itself.
 *
 * <p>The type ids use the {@code world_combat_core} namespace and the line text as the path, so a
 * line {@code cobblemon/orb/orb} registers {@code world_combat_core:cobblemon/orb/orb}. Vanilla
 * particle types already have a SpriteSet and are referenced directly by their own id.
 */
public final class ParticleTypes {
    private static final String NAMESPACE = "world_combat_core";
    private static final String INDEX = "/assets/world_combat_core/particle_types.txt";
    private static final String PREFIX = "cobblemon/";
    private static final List<DeferredHolder<ParticleType<?>, SimpleParticleType>> REGISTERED = new ArrayList<>();

    private ParticleTypes() {}

    /** Creates and registers the deferred particle types; call once from the mod constructor. */
    public static void register(IEventBus bus) {
        if (bus == null) throw new IllegalArgumentException("ParticleTypes.register requires an event bus");
        DeferredRegister<ParticleType<?>> types = DeferredRegister.create(Registries.PARTICLE_TYPE, NAMESPACE);
        for (String path : readIndex()) {
            REGISTERED.add(types.register(path, () -> new SimpleParticleType(false)));
        }
        types.register(bus);
        WorldCombatCore.LOGGER.info("WorldCombat registered {} Cobblemon particle types.", REGISTERED.size());
    }

    /** The registered types, resolved after the registry events have run (client sprite setup). */
    public static List<SimpleParticleType> registeredTypes() {
        List<SimpleParticleType> values = new ArrayList<>(REGISTERED.size());
        for (DeferredHolder<ParticleType<?>, SimpleParticleType> holder : REGISTERED) values.add(holder.get());
        return values;
    }

    /**
     * Reads the generated index, ignoring blanks and comments. Each line is
     * {@code cobblemon/<path> <frames> <w>x<h>}; only the first token names the type, the rest
     * documents the frame layout for authors.
     */
    static List<String> readIndex() {
        List<String> paths = new ArrayList<>();
        for (var entry : index().values()) paths.add(entry.path());
        if (paths.isEmpty()) throw new IllegalStateException("particle_types.txt declares no particle types");
        return paths;
    }

    /** Frame count and per-frame dimensions from the generated Cobblemon atlas grid. */
    public record Layout(String path, int frames, int width, int height) {}
    private static java.util.Map<String, Layout> layouts;

    /** Frame layout for {@code cobblemon/<path>} (with or without the {@code cobblemon/} prefix); null when unknown. */
    public static Layout layout(String path) {
        if (path == null) return null;
        String key = path.startsWith(PREFIX) ? path : PREFIX + path;
        return index().get(key);
    }

    private static synchronized java.util.Map<String, Layout> index() {
        if (layouts != null) return layouts;
        InputStream stream = ParticleTypes.class.getResourceAsStream(INDEX);
        if (stream == null)
            throw new IllegalStateException("Missing particle type index " + INDEX + "; run tools/generate-particle-types.mjs");
        var parsed = new java.util.LinkedHashMap<String, Layout>();
        try (BufferedReader reader = new BufferedReader(new InputStreamReader(stream, StandardCharsets.UTF_8))) {
            String line;
            while ((line = reader.readLine()) != null) {
                String trimmed = line.trim();
                if (trimmed.isEmpty() || trimmed.startsWith("#")) continue;
                String[] tokens = trimmed.split("\\s+");
                String value = tokens[0];
                if (!value.startsWith(PREFIX))
                    throw new IllegalArgumentException("particle_types.txt entry must start with '" + PREFIX + "', got '" + value + "'");
                int frames = 1, width = 0, height = 0;
                if (tokens.length >= 3) {
                    frames = Math.max(1, Integer.parseInt(tokens[1]));
                    String[] size = tokens[2].split("x");
                    if (size.length == 2) { width = Integer.parseInt(size[0]); height = Integer.parseInt(size[1]); }
                }
                parsed.put(value, new Layout(value, frames, width, height));
            }
        } catch (IOException failure) {
            throw new IllegalStateException("Failed to read " + INDEX, failure);
        }
        layouts = parsed;
        return layouts;
    }
}
