// Each short path is the segment actually travelled this tick, not the planned whole route.
WorldCombatParticles.scene("world_combat:move_aerialace",1,{
    interrupt:"hide",moments:{
        gather:{duration:{data:"windup",fallback:5},emitters:[{
            name:"gather",bind:"source",height:.35,particle:"world_combat_core:cobblemon/generic/speedlines",
            rate:24,shape:{kind:"sphere",radius:.35},direction:"inward",speed:.12,lifetime:4,size:[.2,.02],color:0xBDDFFF,alpha:[.65,0],light:"full"
        }]},
        dash:{duration:6,exit:{stop:1,drain:5},emitters:[{
            name:"skim",bind:"path",fit:"world",height:0,particle:"world_combat_core:cobblemon/generic/speedlines",
            shape:{kind:"polyline"},burst:{count:5},speed:0,lifetime:4,size:[.15,.025],color:0x9DC6DF,alpha:[.5,0],light:"full"
        }]},
        return:{duration:6,exit:{stop:1,drain:5},emitters:[{
            name:"back_cut",bind:"path",fit:"world",height:0,particle:"world_combat_core:cobblemon/generic/sparkle/smallsparkle",
            shape:{kind:"polyline"},burst:{count:14},speed:0,lifetime:5,size:[.13,.025],color:0xEAF7FF,alpha:[1,0],light:"full"
        }]},
        hit:{duration:8,exit:{stop:1,drain:7},emitters:[{
            name:"cut_contact",bind:"point",fit:"world",height:0,particle:"world_combat_core:cobblemon/generic/cut",
            burst:{count:1},speed:0,lifetime:7,size:[.65,.15],color:0xDCEEFF,alpha:[1,0],light:"full"
        }]}
    }
});
